In [1]:
import numpy as np
from kingdon import Algebra

# Helper to create a 2D algebra that we will nest
# Signature (0, 1) means e1^2 = -1 (Complex-like)
def make_cd_step(coeffs):
    """
    Takes a list of 2 coefficients (which can be scalars or multivectors)
    and returns a multivector in a 2D algebra.
    """
    alg = Algebra(0, 1)
    # Using 'e' for the identity and 'e1' for the imaginary unit
    return alg.multivector(values=[coeffs[0], coeffs[1]])

print("--- Cayley-Dickson Construction via Nesting ---")

# 1. Level 1: Complex Numbers (C)
# Coefficients are real numbers (floats)
C = make_cd_step([1.0, 2.0])  # 1 + 2i
print(f"Complex (C): {C}")

# 2. Level 2: Quaternions (H)
# Coefficients are Complex Numbers
# q = (1 + 2i) + (3 + 4i)j
H = make_cd_step([
    make_cd_step([1.0, 2.0]), 
    make_cd_step([3.0, 4.0])
])
print(f"Quaternion (H) as C[j]:\n{H}")

# 3. Level 3: Octonions (O)
# Coefficients are Quaternions
# O = H1 + H2 * L (where L is the new octonionic unit)
O = make_cd_step([
    H,                           # Real-part Quaternion
    make_cd_step([               # Imaginary-part Quaternion
        make_cd_step([5.0, 6.0]), 
        make_cd_step([7.0, 8.0])
    ])
])
print(f"\nOctonion (O) as H[L]:\n{O}")

# 4. Extracting the Matrix Connection
print("\n--- Matrix Connection ---")
# The 'real' quaternion matrix
alg_real_H = Algebra(0, 2)
q_real = alg_real_H.multivector(values=[1, 2, 3, 4])
print("Real 4x4 Quaternion Matrix:")
print(q_real.asmatrix())

# The 'nested' matrix (Complex-over-Complex)
print("\nNested 2x2 Matrix (where entries are Complex matrices):")
print(H.asmatrix())

--- Cayley-Dickson Construction via Nesting ---
Complex (C): 1.0 + 2.0 𝐞₁
Quaternion (H) as C[j]:
(1.0 + 2.0 𝐞₁) + (3.0 + 4.0 𝐞₁) 𝐞₁

Octonion (O) as H[L]:
((1.0 + 2.0 𝐞₁) + (3.0 + 4.0 𝐞₁) 𝐞₁) + ((5.0 + 6.0 𝐞₁) + (7.0 + 8.0 𝐞₁) 𝐞₁) 𝐞₁

--- Matrix Connection ---
Real 4x4 Quaternion Matrix:
[[ 1 -2 -3 -4]
 [ 2  1 -4  3]
 [ 3  4  1 -2]
 [ 4 -3  2  1]]

Nested 2x2 Matrix (where entries are Complex matrices):
[[ 1. -3.]
 [ 3.  1.]] + [[ 2. -4.]
 [ 4.  2.]] 𝐞₁
